### ISSUE TITLE
Implement parser with gulp and gulp-nunjucks-render

### ISSUE THREAD

**Issue by evanre** [chocolateboy/nunjucks-parser#1]
Hi, I'm looking for a tool which could help me to optimize rendering of my Nunjucks files.
I'm using combination of gulp, and gulp-nunjucks-render. Also gulp.watch provides me path to njk file which was changed.

Is there a way to render only those pages which has a changed file in dependencies?

Here is example of my 'template' task:
```JavaScript
// argv.html, here is the path to changed file

return $.multipipe(
    gulp.src(config.html.src),
    errorHandler(),
    $.nunjucksRender({
        path: './src/',
        ext: '.html',
        envOptions: {
            autoescape: false,
        },
        manageEnv: njkEnvironment,
    }),
    $.rename((path) => { path.dirname = '/'; }),
    gulp.dest(config.html.dest),
);
```

Thank you.

**Comment by chocolateboy** [comment]
Doesn't nunjucks have this [built in](https://mozilla.github.io/nunjucks/api.html#configure)?

> **watch** (*default: false*) reload templates when they are changed (server-side). To use watch, make sure optional dependency [chokidar](https://www.npmjs.com/package/chokidar) is installed.

**Comment by evanre** [comment]
I'm not sure it fits my needs. I'm using Nunjucks only as a template engine for rendering HTML files in my Front-End development process.

**Comment by chocolateboy** [comment]
I'm not sure what you're trying to do exactly...

If you're using gulp, you must be rendering these templates on the server, which means you can use the [node loader](https://mozilla.github.io/nunjucks/api.html#filesystemloader) and the `watch` option.

Alternatively (or better still), take a look at [parcel](https://github.com/parcel-bundler/parcel#readme) (and [parcel-plugin-nunjucks](https://www.npmjs.com/package/parcel-plugin-nunjucks)), which handles all of this automatically.

**Comment by evanre** [comment]
I'm a Front-End developer. Part of my job is to convert designs into static html pages and pass it to Back-End developers. I'm just using Nunjucks as html-preprocessor (just for convenience and more fast development with bunch of pages among projects).

Now I'm trying to optimize my working gulp-based environment, because after each change in html I must to wait about 5 second while nunjucks are rendering about 50 different pages to see the result in browser.

So, I want to reduce amount of pages and render only those of them which contain changed file.

**Comment by chocolateboy** [comment]
This module just returns a template's dependencies, so I'm not sure how it can help unless you're planning to roll your own template invalidation/regeneration watcher, which, as I say, shouldn't be necessary, as this functionality is already implemented in nunjucks itself.

If everything's working correctly but just taking too long, it might be an issue with [gulp](https://github.com/gulpjs/gulp/issues/1878)/[chokidar](https://github.com/paulmillr/chokidar/issues/328)  (particularly if you're using Windows). I have a similar use case with a similar number of templates and they are updated efficiently (i.e. just the affected dependents) and instantaneously (e.g. a few milliseconds) for me with parcel/parcel-plugin-nunjucks.

**Comment by evanre** [comment]
I hoped I could built with your module a dependency tree (list of all files on the project), and then exclude from this list all items that doesn't have a changed file as dependency. After that I could render only these files and not all pages on project.

**Comment by chocolateboy** [comment]
I'm not sure how that would help (you'd still need to watch all the files in the dependency graph), and it seems like a sticking plaster for a performance issue that's easy to solve in other ways e.g. by using the [`watch` option](https://mozilla.github.io/nunjucks/api.html#configure) or the [parcel plugin](https://www.npmjs.com/package/parcel-plugin-nunjucks).

A third option would be to add dependency-tracking to the gulp plugin, as is done for e.g. [gulp-watch-pug](https://github.com/lishid/gulp-watch-pug). Failing that, you could always create a new one using the same approach e.g. gulp-watch-nunjucks.
