### ISSUE TITLE
Dependencies without rendering

### ISSUE THREAD

**Issue by m-bednar** [chocolateboy/nunjucks-parser#5]
Is there an option to get dependency list **without actually rendering** the template? 
It would be very useful for precompiled/compiled templates.

**Comment by ogonkov** [comment]
```js
var nunjucks = require('nunjucks');

var tokens = nunjucks.parser.parse('<template content'>);

tokens.findAll(nunjucks.nodes.Extends);
```

I didn't found docs for this parser, but here is a full list of nodes, that could load templates:

https://github.com/ogonkov/nunjucks-loader/blob/4ea94a2b77864ab63382cfd976129a0b70ba72df/src/get-dependencies.js#L5

**Comment by m-bednar** [comment]
@ogonkov Nice, that would help me, thanks a lot!

**Comment by chocolateboy** [comment]
Note: though it may work in some cases, there's no way in general to determine the dependencies from the [AST](https://github.com/chocolateboy/nunjucks-parser#why-not): https://github.com/chocolateboy/parcel-plugin-nunjucks/issues/1#issuecomment-423495829

**Comment by ogonkov** [comment]
The case with conditional `include` is handled correctly by `nunjucks.parser`, this one logs `footer.html` node:

```js
var nunjucks = require("nunjucks");

var x = `{% if foo > bar %}
    {% include "footer.html" %}
{% endif %}`;

var t = nunjucks.parser.parse(x);

console.log(t.findAll(nunjucks.nodes.Include));
```

With dynamic include it logs `filename`, it's not clear that it's actually a variable.

**Comment by chocolateboy** [comment]
> The case with conditional include is handled correctly by `nunjucks.parser`

I guess we differ in our definitions of "correctness". I don't consider returning dependencies that aren't used to be "correct":

```javascript
{% set debug = false %}

{% if debug %}
    {% include "debug.html" %}
{% endif %}
```

```javascript
t.findAll(nunjucks.nodes.Include).length // 1
```
Those who are happy to use a solution which doesn't work in general can use the parser, as stated in the [README](https://github.com/chocolateboy/nunjucks-parser#why-not).
